### ISSUE TITLE
Broadcast an email to request the professors to submit their book requests by a certain deadline

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#10]
## What do we need to do for this?

1. Adjust administrator navigation UX to support a button for `Broadcast email reminder` which should link to `broadcast_reminder.php`
~2. UX for `broadcast_reminder.php`~
    ~1. Need to let user pick a date (for the "deadline")~
        ~* Review [`input type="date"` at this link](https://www.w3schools.com/html/html_form_input_types.asp)~
    2. Need button to submit date selection (have it `POST` to `broadcast_reminder.php`)
3. PHP authentication to prevent unauthorized access to this page
    1. PHP sessions support
    2. Query database to validate logged-in user is an admin
        * Need to craft query for this @IvanESanchez
4. PHP retrieve `$_POST` data from date picker
5. PHP query database to get list of email addresses from all `USER`s who are NOT admins
    * @IvanESanchez for query
6. PHP send email to each professor
    1. Email must include some text "reminding" professor to submit their book request
    2. Email must include the date given in `$_POST`
    3. Will clarify how to send email below
7. Show success/failure alert on page (same idea as was used for #7 )

## How to send email

```php
// Load prebuilt mail function from @TerranUp16 
require 'mail.php';

// Loop through email addresses obtained from database query

// Set variables in preparation to pass parameters
$send_to = // Current professor's email address
$subject = // Subject of the email the professor will see; probably something like, "Reminder to Submit Book Requests by " . $deadline_date
$text_body = // Plaintext version of email; use \n for newline; this version is used if recipient disables HTML content
$html_body = // HTML version of email; use <br> for newline; this version is used if recipient has HTML content enabled

// Send email, store boolean which if true means email sent successfully, false means email failed to send
$email_success = send_email($send_to, $subject, $text_body, $html_body);

// At a minimum, be sure to use a flag in the loop so if any email fails to send, you know to give a failure message to user

// Ideally, keep a list of email addresses to which sending failed and provide those as part of the error message to be more helpful to the user
```

**Comment by AndyGarcia102** [comment]
Added broadcast option to admin section.

**Comment by TerranUp16** [comment]
`Broadcast.php` implemented to spec.
