### ISSUE TITLE
The system automatically broadcasts a reminder email by a specified date

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#11]
## What do we need to do for this?

1. Adjust administrator navigation UX to support a button for `Manage automatic email reminders` which links to `manage_reminders.php`
2. @IvanESanchez we need table schema for storing email reminders
    1. Need automatically incrementing primary key
    2. Need date (https://mariadb.com/kb/en/date/)
~3. UX for `manage_reminders.php` @AndyGarcia102 ~
    ~1. Need button to `Create reminder`~
    ~2. Need to show a table of existing reminders~
        ~* Three columns, `id`, `date`, and an unlabeled column which will be used for a `Delete` button for each row~
4. PHP needs to handle authentication (covered in other issues like #6)
5. PHP needs to handle `$_POST` which provides an `id` of a reminder
    1. If this is received, need to delete the provided reminder and show feedback on success or failure of that (see #7 and similar)
~6. Need `create_reminder.php` which has a form UX which asks for a date (see #10 date picker input) and provides a button~ ~to submit that @AndyGarcia102 ~
7. PHP needs to handle authentication, grabbing `GET`/`POST` data, and `INSERT`ing new reminder into database
   * Don't forget to show an alert for success/failure

## TO BE CLEAR

We DO NOT need to actually implement the system having to send the automatic reminders. It would be nice if PHP makes sure the reminders are for future dates though (can't do on UX side without JavaScript) so we are prevented from having derpy-looking entries.

All that is needed here is to manage a very, very simple database table via GUI.

We also do not need to worry about `UPDATE` for these reminders. If someone wants to change the date a reminder is for... they can just delete the reminder and make a new one.

**Comment by AndyGarcia102** [comment]
ManageReminders.php & CreateReminder.php compete the UX requirements.

**Comment by TerranUp16** [comment]
```sql
CREATE TABLE REMINDERS (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL
);
```

**Comment by TerranUp16** [comment]
Fully implemented to spec.
