### ISSUE TITLE
Send an invitation email to a professor to request book information (e.g., an individual reminder)

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#12]
## KEEP IN MIND

This refers directly to-

> When receiving an invitation email to make book requests, click on a URL provided in the email to log in to the book order website. The following two situations may happen:
> * Create a new account if this is the first time using this website
> * Request a temporary password in order to change the current password if forgotten

## What do we need to do for this?

Read over what #10 needs. Make this one `Send invitation` and `send_invitation.php`.

1. ~UX for `send_invitation.php` needs to enable input of an email address and a button to submit (`POST` to `send_invitation.php`)~ @AndyGarcia102
2. PHP needs to handle authentication (covered in other issues like #6)
3. PHP needs to handle `GET`/`POST` data
    1. If an email is provided, keep processing...
4. PHP needs to check if email maps to a known user
    1. If it does, need to remember the `uid` of the user
5. PHP needs to craft text for an email
    1. Did we get a `uid` earlier?
        1. If yes, then make sure the email includes a link to `http://localhost:8080/login.php?uid=X` where `X` is the `uid` obtained
           * Also... make sure `login.php` is updated with logic to prefill the `email`/`username` field with `uid`'s `email` so all the user needs to do is enter their password
        2. If no, then link to `localhost:8080/create_account.php`
    2. #10 clarifies how to send an email

**Comment by AndyGarcia102** [comment]
Created three buttons one for sending a reminder email, another for broadcast, and the final one for requesting information

**Comment by TerranUp16** [comment]
Need to add logic to `login.php` and `newuser.php` for this, but I believe I've finished `sendemail.php` now. Since I'm going to be doing this anyway, I am going to create some JavaScript to modify `placeholder` input fields rather than bother trying to do this with PHP (regarding handling the `GET` parameters from the email links).

**Comment by TerranUp16** [comment]
Done.

Following changes from spec:

1. `SendEmail.php` is a page with two forms
    1. Both forms `POST`s to itself
    2. Embedded PHP on page differentiates between which form was submitted based on what parameters are in `$_POST`
    3. Handles both invitations and reminders
2. `SendEmail.php` only handles `POST` data right now
    * Probably all it needs to handle as this is what the buttons are setup to enable
3. `SendEmail.php` does not bother remembering `uid`
    * Original expectation was this would need to be more database-driven
    * While using `uid` would have saved some `urlencode` lines, it would have entailed another database query, so not worth it
    * Using `email` instead which is a unique key in `USER` and therefore acceptable (but also is what's supplied so when query parameters embedded into emails are activated, it just does what the user gave it input for)
    * Using user input to prefill `email` fields in login/new user forms ends up being fine as there is no auto-login with this, so user can see what was prefilled and modify it as needed (and it's also subject to normal `login.php` and `NewUser.php` validation)
