### ISSUE TITLE
View the list of requests for a given semester (including the upcoming semester)

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#14]
## What do we need to do for this?

**WIP** - will update this more later, but wanted to at least get a stub down before bed.

This needs three parts-

1. ~Button in admin UX to `View Requests for Semester` or something like that~
2. Form to select a semester
    1. This is moderately a pain in the butt
    2. Going to want query `SEMESTER` table from database to get the union of `year` and `season` (and I recommend doing so in sorted, ascending order)
    3. PHP can use the results of this query to create a [`select`](https://getbootstrap.com/docs/5.1/forms/select/) element with all, possible semester options
       * Hint- if the query presorts correctly, you can loop through the results one at a time and in the loop, you can create each `option` element; be smart and make each option's `value` a string which combines `season` and `year`, ex- `Summer 2019`; let the order you add `option` elements take care of "sorting" for you
    4. Obviously need a button to submit that selection and `POST` to a new `view_semester.php` or whatever
3. Page to display requests from the given semester
    1. Only downside of being sensible about `select` `option`s is PHP will need to [`explode`](https://www.php.net/manual/en/function.explode) the given parameter using `' '` as the delimeter to fetch year and season separately
    2. Need to query database to get all book requests from the given semester
    3. Output style should be identical to #13 except the main page header will display the semester and then professor names will headline each book list table

**Comment by AndyGarcia102** [comment]
AdminFinal.php
