### ISSUE TITLE
The first form, after login, asks if the professor wants to submit a new book request form, or view and edit an existing form

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#16]
## What do we need to do for this?

1. UX to show buttons for `Submit a new book request form` and `View/Edit existing form`
2. PHP needs to handle authentication
    * Just need to ensure user is logged-in via PHP session

**Comment by AndyGarcia102** [comment]
MainMenu.php

**Comment by TerranUp16** [comment]
Done to spec.
