### ISSUE TITLE
Fill out a new online book request form. For each class, enter the following order information for each book: (1) book title, (2) author names, (3) edition, (4) publisher, (5) ISBN. The system maintains only one request form for each professor for a given semester.

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#17]
## What do we need to do for this?

This one needs a lot. Going to break it down into sub-headers.

### Upfront schema clarification

Project's descriptions for this are awful and non-deterministic. For example-

> The system maintains only one request form for each professor for a given semester.

This would mean one professor can have multiple book requests. However, the very next set of bullets includes (emphasis mine)-

> View and edit **the** existing request form
> ...
> Delete **the** current request form (This allows creation of a new form)

These sets of bullets are logically incoherent. One states professors can have a book request per semester, the other states that only one book request per professor can ever exist.

So how are we going to handle that? We're going with the first definition. It's more work, but it's less likely to get us docked points.

The way our schema handles that is a hierarchy of-

* Book Requests maps users/professors to semesters and book lists (`uid` and `skey` combine to form a `UNIQUE KEY` which prevents this table from storing rows featuring identical professor and semester combinations)
* Book Lists maps book requests to books
* Books are just objects which contain the data the requirements dictate

### How does making a new book request form work?

Again, project requirements suck here. The good news is the project requirements do not say anything about needing to display the request as books are added to it. Also, while it kinda breaks the spirit of the `for each class` thing, because all that is asked of this page is to provide a way to specify what `class` (which should be interpreted as `professor + semester`) the book is for and what the details of a single book are...

The form should really just be a way to add a book. Ignore the entire concept of "creating a new book request form". All we are doing is providing an interface which-

* Creates a book (if needed)
   * Leverage [`INSERT ON DUPLICATE KEY UPDATE`](https://mariadb.com/kb/en/insert-on-duplicate-key-update/) for this; yes, this means if someone submits an `ISBN` which already exists, existing book will be overwritten; point of this is it gives new functionality to modify an existing book (functionality we don't otherwise expose)
* Creates a new book request (if needed)
   * Obviously, check if the existing `uid` and semester combination exist in `BOOK_REQS`
* Adds an entry to `BOOK_LIST` to associate the new/updated book with the new/existing book request

So again, in reality, you can kinda just plug in whatever semester and book information you want, press submit, and then you can enter a different semester when the page reloads so you are now "adding to a different book list", and that's why this is "weird", but meh.

### UX Needs

`BookForm.html` handles the UX requirement for this. Just have an additional, PHP-side UX item that if a `POST` is processed, need to display like in #8 whether the operation succeeded or failed.

### PHP Needs

1. PHP authentication like in #16 
2. Check for `GET`/`POST` data
    1. If such exists...
    2. Leverage [`INSERT ON DUPLICATE KEY UPDATE`](https://mariadb.com/kb/en/insert-on-duplicate-key-update/) to create a new book/update an existing book
    3. Check if a book request for the given `uid` and semester combination exists or not
        * PHP will need to use [`explode`](https://www.php.net/manual/en/function.explode) to separate year and season data from `semester` input
        * @IvanESanchez, please help with the query for this as it will need to find `skey` from `SEMESTER` by using `year` and `season` and leverage professor's `uid` (obtained from PHP session) and obtained `skey` to check `BOOK_REQS` for an existing `brid`
    4. If the book request does not exist, `INSERT` it (and retrieve its `brid`)
    5. If the book request exists, obtain its `brid`
    6. `INSERT` an entry into `BOOK_LIST` mapping `brid` of book request and the `bid` of the book

**Comment by AndyGarcia102** [comment]
BookForm.php handles the ux

**Comment by TerranUp16** [comment]
Done to spec.
