### ISSUE TITLE
View and edit the existing request form

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#18]
> * Delete one or more books from the current request form
> * Add one or more books to the current request form
> * Delete the current request form (This allows creation of a new form)

## What do we need to do for this?

Let's first walk through how, conceptually, we can satisfy the requirements given with just two pages-

> View and edit **the** existing request form

We don't have a 1:1 mapping per professor. Therefore, we need a page enabling a professor to select what semester's book request form they want to view.

This will use knowledge of the `uid` of the professor/user from PHP sessions to query `BOOK_REQS` to get all `skey` values `WHERE uid=` the `uid` we have from our session. PHP can use `skey` to fetch `year` and `season` from `SEMESTER` to display table of semesters customized for the professor with an `Edit/View` button next to each.

For the below requirements, assume the user has already chosen what semester's form to edit/view.

> Delete one or more books from the current request form

Show each book associated with the current book request in a table. Show a `Delete` button next to each book.

TO BE CLEAR, DO NOT `DELETE ... FROM BOOK`. INSTEAD, `DELETE ... FROM BOOK_LIST`. This will disassociate the book from the book request without deleting our knowledge of the book itself.

> Add one or more books to the current request form

Just toss a button somewhere on the page called `Add Books` that links to #17.

> Delete the current request form (This allows creation of a new form)

Make a button, probably next to the `Add Books` button, for `Delete Request`. Have it `GET` to #17 page with `?delete=brid` where `brid` is this book request's id. Then add new functionality to #17 page to detect that `GET` parameter and to process `DELETE FROM` statements targeting the `brid` in `BOOK_LIST` and `BOOK_REQS`.

### UX

~Review the above, revised requirements. Make a header element (which PHP will populate with text for the semester). Make~ ~the "global" buttons for `Add Books` and `Delete Request`. Make the `<table>` element which will hold the books. Include a~ ~`<tr>` inside with `<th>` elements defining columns for:~

~* Book Title~
~* Author Names~
~* Edition~
~* Publisher~
~* ISBN~

### PHP

1. PHP authentication like in #16 
2. Check `GET` data for a `bid`
    1. If such exists...
    2. `DELETE FROM BOOK_LIST WHERE bid = ` the `bid` given
    3. Display like from #8 success/failure of this process
3. Dynamically populate header element with this semester's `year` and `season`
4. Add a row to `<table>` for each book from this `brid` in `BOOK_LIST`
    * Add an extra `<td>` per row which contains a `<button>` element which submits to this page with `?delete=bid` where `bid` comes from the book the row is for

**Comment by AndyGarcia102** [comment]
Created Ux. BookSearch.php
