### ISSUE TITLE
Shift professor navigation panel to PHP template

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#2]
`MainMenu.html` has a navigation bar on the left side.

Please create `navbar.php`.

Treat this as a partial HTML file. Do not make `<html>`, `<head>`, or `<body>` tags for these. Just start with `<nav>`.

Using current code, this would look like-
```
<div class="side-bar">
  <h2>Menu<ul>Options</h2>
  <ul>
    <li><a href="MainMenu.html"><img src="house-fill.svg" alt="Home" width="15"> Home</a></li>
    <li><a href="BookForm.html"><img src="book.svg" alt="book-order" width="15"> Book request form</a></li>
    <li><a href="#"><img src="list.svg" alt="book-request" width="15"> View list of requests</a></li>
    <li><a href="#"><img src="bookshelf.svg" alt="book-list" width="15"> Edit book forms</a></li>
    <li><a href="SendEmail.html"><img src="envelope.svg" alt="invitaion-email" width="15"> Send invitaion</a></li>
    <li><a href="index.html">Log out</a>
  </ul>
</div>
```

This file can then be included via PHP.

**Comment by AshenSilverwolf** [comment]
- MainMenu.html has been replaced by MainMenu.php
- navbar.php has been added to templates/
- MainMenu.php references templates/navbar.php for the navbar components

* Stylesheets don't seem to work with this
