### ISSUE TITLE
Log in to the system as a super admin (i.e., the first admin user) using a predefined password

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#5]
## What do we need for this?

1. ~Environment contains data/secrets necessary to initialize super admin~
2. ~Database schema~
3. ~Database schema initialization~
4. ~Super admin user initialization~
5. ~UX for login page~
6. Working login page
    1. PHP session management
    2. Query database to validate submitted `email` and `password` data
        * Need to craft the query needed for this @IvanESanchez

**Comment by AshenSilverwolf** [comment]
Can log in as Super Admin or as any other user logged in the database

Note: redirects to adminmenu.html or mainmenu.php based on admin status
