### ISSUE TITLE
Delete an existing admin account

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#7]
## What do we need to do for this?

~1. UX for delete user page @AndyGarcia102~ 
    * Show table of current users
       * Use PHP to dynamically display rows of users
       * Query MariaDB for `email` and `name` fields for each user @IvanESanchez 
       * Provide a `Delete` button next to each user
          * Each button should have an `action` to `GET` to this page with query parameter specifying the `uid` of the user to delete
2. PHP authentication to prevent unauthorized access to this page
    1. PHP sessions support
    2. Query database to validate logged-in user is an admin
        * Need to craft query for this @IvanESanchez
3. PHP needs to check for `$_GET` and `$_POST` data for `uid`
   1. If found, PHP needs to...
   2. Query MariaDB to `DELETE FROM USER WHERE uid = ` the `uid` retrieved from `$_GET` or `$_POST`
   3. Display a message like a [Bootstrap `success` alert](https://getbootstrap.com/docs/5.1/components/alerts/) on the page to let the user know the user was removed successfully (assuming query succeeded)
   4. Display a message like a [Bootstrap `danger` alert](https://getbootstrap.com/docs/5.1/components/alerts/) if the query failed
   5. Rest of UX should remain as-is so user can see list of users and delete another user if desired

**Comment by AndyGarcia102** [comment]
Created the UX for the delete user form.

**Comment by TerranUp16** [comment]
Done.
