### ISSUE TITLE
Change the password as needed

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#8]
## What do we need to do for this?

Refer to #7. Make a page that is identical to that except-

1. Instead of a `Delete` button, make a `Manage Account` button for each user
2. Set the button up to feed the `uid` as a query parameter (`$_GET` variable) to `manage_account.php`
3. ~Create UX for Manage Account page~
4. Use PHP to see if `uid` supplied via `GET` or `POST`
    1. If yes, then display modified page UX which shows the `email` of the user being modified
        * This will require a database query @IvanESanchez 
    2. If no, leave default UX (which assumes the logged-in user is managing their own account)
5. PHP authentication to prevent unauthorized access to this page
    1. PHP sessions support
    2. If trying to modify a user other than the logged-in user...
         * Query database to validate logged-in user is an admin
             * Need to craft query for this @IvanESanchez 
6. ~UX needs to `POST` to this page when user submits changes~
7. PHP validate form input via regex to ensure input data will work based on schema for `USER`
    * SANITIZE ALL INPUT IN PREPARATION FOR DATABASE QUERY
    * Review `mysqli` documentation on `real_escape_string` method/function
8. PHP identify what form fields were submitted/modified
    1. For each form submitted/modified...
    2. Perform `UPDATE` query to make needed changes to `USER` table
    3. Display a message like a [Bootstrap `success` alert](https://getbootstrap.com/docs/5.1/components/alerts/) on the page to let the user know the user was removed successfully (assuming query succeeded)
    4. Display a message like a [Bootstrap `danger` alert](https://getbootstrap.com/docs/5.1/components/alerts/) if the query failed
    5. Rest of UX should remain as-is so user can perform further modifications if desired

**Comment by AndyGarcia102** [comment]
Completed my UX parts from this issue.

**Comment by TerranUp16** [comment]
Done.
