### ISSUE TITLE
Create and maintain the faculty database that includes at least their name and email address

### ISSUE THREAD

**Issue by TerranUp16** [IvanESanchez/COP4710-Final-Project#9]
## What do we need to do for this?

This should be covered by #6, #7, and #8.

* @AndyGarcia102, please make sure that #8 includes `Change Name` separately from `Change Email` and `Change Password`
   * I know this goes against what we said at the meeting on 12/2, but... further review of this project's disjointed requirements - _ -

**Comment by AndyGarcia102** [comment]
Updated manage account page.
